Build appimage workflow update Workflow is now reusable

diff --git a/.github/workflows/build-appimage.yml b/.github/workflows/build-appimage.yml
--- a/.github/workflows/build-appimage.yml
+++ b/.github/workflows/build-appimage.yml
@@ -3,14 +3,14 @@ name: Build AppImage
 on:
   workflow_dispatch:
     inputs:
+      package-name:
+        description: "Bambu AppImage name"
+        required: true
+        default: "bambu-gcc7_clang11"
       branch:
         description: "Repository branch to build from"
         required: false
         default: "main"
-      version:
-        description: "Bambu version identifier"
-        required: true
-        default: "gcc7_clang11"
       compilers:
         description: "Comma separated list of compilers to include"
         required: true
@@ -24,16 +24,47 @@ on:
         required: true
         default: "--enable-glpk --enable-flopoco --enable-opt --with-opt-level=2 --enable-release CC=gcc-8 CXX=g++-8 --with-gcc8=/bin/false"
 
-concurrency:
-  group: build-appimage-${{ github.event.inputs.version }}
-  cancel-in-progress: true
+  workflow_call:
+    inputs:
+      package-name:
+        description: "Bambu AppImage package name"
+        required: true
+        type: string
+      compilers:
+        description: "Comma separated list of compilers to include"
+        required: false
+        type: string
+        default: "gcc-7,clang-12"
+      build-compiler:
+        description: "Compiler used to build bambu (if not already included in compilers)"
+        required: false
+        type: string
+        default: "gcc-8"
+      configure:
+        description: "Bambu configuration options"
+        required: false
+        type: string
+        default: "--enable-glpk --enable-flopoco --enable-opt --with-opt-level=2 --enable-release CC=gcc-8 CXX=g++-8 --with-gcc8=/bin/false"
+    secrets:
+      CI_STORAGE_URL:
+        required: true
+      CI_STORAGE_USER:
+        required: true
+      CI_STORAGE_TOKEN:
+        required: true
+    outputs:
+      package-name: ${{env.package-name}}
 
 env:
+  compilers: ${{inputs.compilers}}${{github.event.inputs.compilers}}
+  build-compiler: ${{inputs.build-compiler}}${{github.event.inputs.build-compiler}}
+  configure: ${{inputs.configure}}${{github.event.inputs.configure}}
+  compilers-dist-url: https://release.bambuhls.eu:8080/compiler
   storage-url: ${{secrets.CI_STORAGE_URL}}
   storage-user: ${{secrets.CI_STORAGE_USER}}
   storage-token: ${{secrets.CI_STORAGE_TOKEN}}
   storage-path: release
-  dist-pkg: bambu-${{github.event.inputs.version}}
+  package-name: ${{inputs.package-name}}${{github.event.inputs.package-name}}
   dist-dir: dist
   bcompiler-dir: compiler
   host_jobs: $J
@@ -52,25 +83,6 @@ jobs:
         run: |
           echo "Current host supports ${{env.host_jobs}} parallel jobs"
           echo "::set-output name=jobs::${{env.host_jobs}}"
-      - name: Compilers download configuration
-        id: compilers
-        shell: bash
-        run: |
-          IFS=',' read -r -a compilers <<< "${{github.event.inputs.compilers}}"
-          for compiler in "${compilers[@]}"
-          do
-            echo "::set-output name=$compiler::1"
-          done
-          mkdir ${{env.dist-dir}}
-      - name: Build compiler configuration
-        id: bcompiler
-        shell: bash
-        run: |
-          if [[ ! -z "${{github.event.inputs.build-compiler}}" ]]
-          then
-            mkdir ${{env.bcompiler-dir}}
-            echo "::set-output name=${{github.event.inputs.build-compiler}}::1"
-          fi
       - name: Download compilers
         shell: bash
         run: |
@@ -108,58 +120,73 @@ jobs:
                 wget https://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -nv -O - | tar -C $2 -xJf - &
                 ;;
               gcc-4.5 )
-                wget https://release.bambuhls.eu:8080/compiler/gcc-4.5-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
+                wget ${{env.compilers-dist-url}}/gcc-4.5-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                 ;;
               gcc-4.6 )
-                wget https://release.bambuhls.eu:8080/compiler/gcc-4.6-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
+                wget ${{env.compilers-dist-url}}/gcc-4.6-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                 ;;
               gcc-4.7 )
-                wget https://release.bambuhls.eu:8080/compiler/gcc-4.7-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
+                wget ${{env.compilers-dist-url}}/gcc-4.7-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                 ;;
               gcc-4.8 )
-                wget https://release.bambuhls.eu:8080/compiler/gcc-4.8-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
+                wget ${{env.compilers-dist-url}}/gcc-4.8-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                 ;;
               gcc-4.9 )
-                wget https://release.bambuhls.eu:8080/compiler/gcc-4.9-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
+                wget ${{env.compilers-dist-url}}/gcc-4.9-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                 ;;
               gcc-5 )
-                wget https://release.bambuhls.eu:8080/compiler/gcc-5-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
+                wget ${{env.compilers-dist-url}}/gcc-5-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                 ;;
               gcc-6 )
-                wget https://release.bambuhls.eu:8080/compiler/gcc-6-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
+                wget ${{env.compilers-dist-url}}/gcc-6-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                 ;;
               gcc-7 )
-                wget https://release.bambuhls.eu:8080/compiler/gcc-7-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
+                wget ${{env.compilers-dist-url}}/gcc-7-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                 ;;
               gcc-8 )
-                wget https://release.bambuhls.eu:8080/compiler/gcc-8-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
+                wget ${{env.compilers-dist-url}}/gcc-8-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                 ;;
               * )
+                echo "Unknown compiler required"
+                exit 1
                 ;;
             esac
           } 
-          IFS=',' read -r -a compilers <<< "${{github.event.inputs.compilers}}"
+          IFS=',' read -r -a compilers <<< "${{env.compilers}}"
           compilers=( $(IFS=$'\n'; echo "${compilers[*]}" | sort -V) )
+          mkdir ${{env.dist-dir}}
           for compiler in "${compilers[@]}"
           do
             inflate $compiler ${{env.dist-dir}}
           done
           wait
-          if [[ ! -z "${{github.event.inputs.build-compiler}}" ]]
+          if [[ ! -z "${{env.build-compiler}}" ]]
           then
-            inflate ${{github.event.inputs.build-compiler}} ${{env.bcompiler-dir}}
+            mkdir ${{env.bcompiler-dir}}
+            inflate ${{env.build-compiler}} ${{env.bcompiler-dir}}
           fi
           wait
       - name: Build Bambu application
         id: build
         uses: ./.github/actions/generate-bin
         with:
-          config-args: ${{github.event.inputs.configure}} --enable-Werror
+          config-args: ${{env.configure}} --enable-Werror
           jobs: ${{steps.host.outputs.jobs}}
-      - name: Upload Panda install directory
+      - name: Upload PandA Bambu HLS AppImage for CI
+        if: ${{ inputs.package-name != "" }}
+        uses: ./.github/actions/storage-upload
+        with:
+          name: ${{env.package-name}}
+          path: ${{steps.build.outputs.appimage}}
+          storage-url: ${{env.storage-url}}
+          username: "${{env.storage-user}}"
+          password: "${{env.storage-token}}"
+          storage-compression: false
+      - name: Upload Panda Bambu HLS Release
+        if: ${{ github.event.inputs.package-name != "" }}
         shell: bash
         run: |
-          APP_FILE="${{env.dist-pkg}}.AppImage"
+          APP_FILE="${{env.package-name}}.AppImage"
           STORAGE_URL="${{env.storage-url}}/${{env.storage-path}}/$APP_FILE"
           curl -L --fail -u '${{env.storage-user}}':'${{env.storage-token}}' -T "${{steps.build.outputs.appimage}}" "$STORAGE_URL"
-          echo "::notice New release available at https://release.bambuhls.eu:8080/appimage/$APP_FILE"
+          echo "::notice:: New release available at https://release.bambuhls.eu:8080/appimage/$APP_FILE"
